[book]
authors = []
language = "en"
src = "src"
title = "How to Pray the Rosary"
description = "How to pray the Rosary"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"

[preprocessor.image-size]
command = "mdbook-image-size"

